### PR TITLE
Run CI using GitHub actions

### PR DESCRIPTION
**Pull request by nullobject**
This PR updates the project to run CI using GitHub actions, instead of Travis CI.

It adds workflows for both running tests and publishing a package to NPM when a new release is tagged. I also added an [organisation secret](https://github.com/organizations/conversation/settings/secrets/actions) for the NPM token.

See also:

- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
- https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

## How to review

* Check that CI is running in workflows
* I'm not sure how we can test the publishing workflow, we might have to try it and adjust? I'm open to ideas.

### CODE REVIEW

**Comment by jameshill** [comment]
Screen Shot 2021-11-23 at 3 26 54 pm

I wonder if it's unlimited for public repos? i assume?

**Comment by jameshill** [comment]
Screen Shot 2021-11-23 at 3 28 33 pm

ah yes.. it is.

**Comment by tiagoamaro** [comment]
Awesome @nullobject! This is quite nice! I'm going to make a small commit in this PR to change the badge as well, since we are no longer going to use Travis.

**Review by tiagoamaro — APPROVED** [review]
LGTM!

**Pull request merged**
